// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Gowun_Dodum } from "next/font/google";

const DoHyeon = Gowun_Dodum({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={DoHyeon.className}>{children}</body>
    </html>
  );
}
