// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Gowun_Dodum } from "next/font/google";

const DoHyeon = Gowun_Dodum({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={DoHyeon.className}>{children}</body>
  </html>
);

export default RootLayout;
