// app/layout.tsx (혹은 RootLayout.tsx)
import type { Metadata } from "next";
import "./globals.css";
import { Gowun_Dodum } from "next/font/google";
import { SocketProvider } from "@/hooks/SocketProvider";

const DoHyeon = Gowun_Dodum({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={DoHyeon.className}>
        <SocketProvider>{children}</SocketProvider>
      </body>
    </html>
  );
}
